name: gitactiondemo 
on:
   push:
 
     branches:
        -main

jobs:
    jobs-extract: 
        
           runs-on: ubuntu-latest 

           steps:

           name: checkout code 
           uses: actions/checkout@v4

           name: e.py 
           run: python e.py

jobs:
    jobs-transfrom: 
        
           runs-on: ubuntu-latest 

           steps:

           name: checkout code 
           uses: actions/checkout@v4

           name: t.py
           run: python t.py

jobs:
    jobs-load: 
        
           runs-on: ubuntu-latest 

           steps:

           name: checkout code 
           uses: actions/checkout@v4

           name: l.py
           run: python l.py           
