name: gitactiondemo

on:
  push:
    branches:
      - main

jobs:

  jobs-extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run extract script
        run: python e.py

  jobs-transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run transform script
        run: python t.py

  jobs-load:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run load script
        run: python l.py
